### ISSUE TITLE
More tips

### ISSUE THREAD

**Issue by Tarliton** [mh-cbon/go-get-started#1]
As yourself, I had some trouble getting started with go. You might want to check for golint, go vet and lots of others go tool commands (they are really usefull and they really should be mentioned is this repo).

Using go vet in your code example I could see one thing that a few days ago I went through as well.

`go vet`
`can't load package: /home/morwar/.gvm/pkgsets/go1.6.2/global/src/github.com/mh-cbon/a/main.go:4:2: local import "./a" in non-local package`

you can fix that using the full path to your package `a` inside of package `a`, like this:

```
package main

import (
    "github.com/mh-cbon/a/a"
)

func main() {
    a.Hello()
}
```

I don't know if this is the way to do it, but if go vet don't warn us about that, we should be in the right path.

Thanks and happy coding!

**Comment by mh-cbon** [comment]
Yep indeed you have right!

I double check with [this](http://stackoverflow.com/questions/30885098/go-local-import-in-non-local-package) and [that](https://golang.org/cmd/go/#hdr-Relative_import_paths), clearly this was bad guidance.

I ll check [golint](https://github.com/golang/lint) soon.

thanks!
